name: "Code Analysis"

on:
  push:
    branches: [main, dev]

  pull_request:
    branches: [main, dev]

  workflow_dispatch:

jobs:
  codeql:
    runs-on: windows-latest

    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2

      - name: Build
        run: |
          cmake -S . -B ./build -A x64  -DPWN_BUILD_TOOLKIT=OFF- PWN_INCLUDE_DISASSEMBLER=OFF -DPWN_ENABLE_LUA_BACKDOOR=OFF -DPWN_BUILD_DOCS=OFF -DPWN_BUILD_TESTING=OFF 
          cmake --build ./build --verbose --config Debug

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
