name: CI Dev Build for MSVC

env:
  ARCH: x64

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: "Building pwn++ (dev)"
    runs-on: [windows-latest]
    strategy:
      fail-fast: true

    steps:
    - uses: actions/checkout@v2

    - name: Build Capstone lib
      shell: pwsh
      run: |
        Import-Module .\.github\Invoke-VS.ps1
        cd ..
        git clone https://github.com/aquynh/capstone
        cd .\capstone\msvc
        Invoke-VisualStudio2019${{ env.ARCH }}
        devenv capstone.sln -nologo /resetsettings
        devenv capstone.sln -nologo /upgrade
        msbuild capstone_static/capstone_static.vcxproj -m -nologo /p:Configuration="Release" /p:Platform=${{ env.ARCH }}


    - name: Build Keystone lib
      shell: pwsh
      run: |
        Import-Module .\.github\Invoke-VS.ps1
        cd ..
        git clone https://github.com/keystone-engine/keystone
        Invoke-VisualStudio2019x64
        mkdir .\keystone\build
        cd .\keystone\build
        ..\nmake-lib.bat


    - name: Build pwn++ DLL
      shell: pwsh
      run: |
        Import-Module .\.github\Invoke-VS.ps1
        New-Item -ItemType SymbolicLink -Target "..\pwn--" -Path "..\pwn++" -ErrorAction Continue
        Invoke-VisualStudio2019x64
        msbuild pwn++\pwn++.vcxproj -nologo /m /p:Configuration=Release /p:Platform=x64


    - name: Prepare artifact
      id: prepare_artifact
      shell: pwsh
      run: |
        mkdir build\
        mkdir build\include\
        cp pwn++\x64\Release\pwn++.lib build\
        cp pwn++\x64\Release\pwn++.dll build\
        cp pwn++\*.h build\include\


    - name: Publish artifact
      id: publish_artifact
      uses: actions/upload-artifact@v2
      with:
        name: pwn++_msvc_${{ env.ARCH }}_${{ github.sha }}
        path: build\
