name: "Issues/PRs Notification"

on:  issues

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}


jobs:
  notify:
    runs-on: ubuntu-latest
    steps:

      - name: Triggering Issue Discord Notification
        if: github.event_name == 'issues' && github.event.action == 'opened' && github.repository_owner == 'hugsy'
        uses: sarisia/actions-status-discord@v1
        with:
          nodetail: true
          title: "[${{ github.repository }}] ${{ github.actor }} created a new Issue (`#${{ github.event.issue.number }}`)"
          description: |
            **${{ github.event.issue.title }}**

            ${{ github.event.issue.body }}

            ---
            Link: ${{ github.event.issue.html_url }}
          color: 0xff0000
          username: ${{ github.actor }} via GithubBot
          avatar_url: ${{ github.actor.avatar_url }}
